<?php

// ----------------------------- //
// ------ Standard Colors ------ //
// ----------------------------- //

$standard_default_text_color = industrium_get_prefered_option('standard_default_text_color');
if ( !empty($standard_default_text_color) ) {
    $industrium_custom_css .= '
        .content-wrapper,
        .block-editor-block-list__layout,
        .single-post .post-meta-footer .post-meta-item.post-meta-item-tags a,
        .project-item-wrapper .project-item-categories,
        .project-item-wrapper .project-item-categories a,
        .industrium-price-item-widget .price-item .price-item-custom-field.active,
        .widget_categories ul li:hover li,
        .content-wrapper input[type="text"],
        .content-wrapper input[type="email"],
        .content-wrapper input[type="url"],
        .content-wrapper input[type="password"],
        .content-wrapper input[type="search"],
        .content-wrapper input[type="number"],
        .content-wrapper input[type="tel"],
        .content-wrapper input[type="range"],
        .content-wrapper input[type="date"],
        .content-wrapper input[type="month"],
        .content-wrapper input[type="week"],
        .content-wrapper input[type="time"],
        .content-wrapper input[type="datetime"],
        .content-wrapper input[type="datetime-local"],
        .content-wrapper input[type="color"],
        .content-wrapper select,
        .content-wrapper .select2-container .select2-selection--single,
        .content-wrapper textarea,
        .block-editor-block-list__layout input[type="text"],
        .block-editor-block-list__layout input[type="email"],
        .block-editor-block-list__layout input[type="url"],
        .block-editor-block-list__layout input[type="password"],
        .block-editor-block-list__layout input[type="search"],
        .block-editor-block-list__layout input[type="number"],
        .block-editor-block-list__layout input[type="tel"],
        .block-editor-block-list__layout input[type="range"],
        .block-editor-block-list__layout input[type="date"],
        .block-editor-block-list__layout input[type="month"],
        .block-editor-block-list__layout input[type="week"],
        .block-editor-block-list__layout input[type="time"],
        .block-editor-block-list__layout input[type="datetime"],
        .block-editor-block-list__layout input[type="datetime-local"],
        .block-editor-block-list__layout input[type="color"],
        .block-editor-block-list__layout select,
        .block-editor-block-list__layout .select2-container .select2-selection--single,
        .block-editor-block-list__layout textarea,
        .select2-container--default .select2-search--dropdown .select2-search__field,
        body .select2-container--default .select2-search--dropdown .select2-search__field,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form select,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form select,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea,
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected],
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected], 
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .select2-container--default .select2-selection--single .select2-selection__rendered,
        .block-editor-block-list__layout .select2-container .select2-results__option,         
        .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected],
        .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected],
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected], 
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .select2-container--default .select2-selection--single .select2-selection__rendered,
        .content-wrapper .select2-container .select2-results__option, 
        .select2-container .select2-results__option,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"],
        .site-search .search-form .search-form-field,        
        .industrium-format-quote .post-quote,
        .industrium-format-quote .post-quote:hover {
            color: ' . esc_attr($standard_default_text_color) . ';
        }
    ';
}

$standard_dark_text_color = industrium_get_prefered_option('standard_dark_text_color');
if ( !empty($standard_dark_text_color) ) {
    $industrium_custom_css .= '
        .content-wrapper h1,
        .content-wrapper h2,
        .content-wrapper h3,
        .content-wrapper h4,
        .content-wrapper h5,
        .wpforms-form .wpforms-title,
        .content-wrapper h6,
        .block-editor-block-list__layout h1,
        .block-editor-block-list__layout h2,
        .block-editor-block-list__layout h3,
        .block-editor-block-list__layout h4,
        .block-editor-block-list__layout h5,
        .block-editor-block-list__layout h6,
        .content-wrapper a:hover,        
        .content-wrapper .wrapper-socials a,
        .content-pagination .page-numbers,
        .content-pagination .post-page-numbers,
        body .content-wrapper .wp-block-pullquote,
        .block-editor-block-list__layout .wp-block-pullquote,
        body .industrium_comments__item-text blockquote,
        .content-wrapper .post-title,
        .content-wrapper .post-title a,
        .block-editor-block-list__layout .post-title,
        .block-editor-block-list__layout .post-title a,
        .owl-theme .owl-nav [class*="owl-"]:before,
        .post-comment-author,        
        .widget_search .search-form .search-form-icon,
        .widget_categories ul li > a, 
        body .content-wrapper ul.wp-block-categories li > a,
        .widget_categories ul li .widget-archive-trigger, 
        .widget_categories ul li .block-archive-trigger, 
        body .content-wrapper ul.wp-block-categories li .widget-archive-trigger, 
        body .content-wrapper ul.wp-block-categories li .block-archive-trigger,
        .block-editor-block-list__layout ul.wp-block-categories li > a, 
        .block-editor-block-list__layout ul.wp-block-categories li .widget-archive-trigger, 
        .block-editor-block-list__layout ul.wp-block-categories li .block-archive-trigger,
        .widget_industrium_featured_posts_widget .featured-posts-item-link,
        .widget_archive ul li > a,
        .wp-block-archives li > a,
        body .content-wrapper .wp-block-archives li > a,
        .widget_recent_entries ul li a,
        .content-wrapper .wp-block-latest-posts li a,
        .widget_recent_comments ul .recentcomments a,
        .content-wrapper .wp-block-latest-comments li a,  

        .block-editor-block-list__layout .wp-block-archives li > a,
        .block-editor-block-list__layout .wp-block-latest-posts li a,
        .block-editor-block-list__layout .wp-block-latest-comments li a,      
        .widget_tag_cloud .tagcloud .tag-cloud-link,
        .wp-block-tag-cloud .tag-cloud-link,
        .widget_pages .widget-wrapper > ul li > a,
        .widget_meta ul li > a,
        .sidebar .widget .widget-title a,
        .widget_rss cite,
        .widget_rss ul a.rsswidget,
        .wp-block-rss .wp-block-rss__item-title a,
        .wp-block-rss .wp-block-rss__item-author,
        .widget_nav_menu ul li .widget-menu-trigger, 
        .widget_industrium_nav_menu_widget ul li .widget-menu-trigger,
        .widget_nav_menu ul li a, 
        .widget_industrium_nav_menu_widget ul li a,
        .portfolio-post-meta .portfolio-post-meta-label,
        .post-navigation .post-navigation-title a,
        .post-navigation .archive-icon-link .archive-icon,
        .team-experience-item-title,
        .team-item .post-title,
        .project-item-wrapper .post-title,
        .project-post-meta .project-post-meta-label,
        .vacancy-salary .vacancy-salary-value,
        .header-icon.login-logout a.link-login, 
        .header-icon.login-logout a.link-logout,
        .help-item .help-item-title,
        .service-item .service-post-title a,
        .industrium-price-item-widget .price-item.price-item-type-wide .price-item-title,
        .elementor-counter .elementor-counter-title,
        .industrium-testimonial-carousel-widget .testimonial-carousel-wrapper .author-name,
        .elementor-widget-accordion .elementor-accordion .elementor-tab-title .elementor-accordion-title,
        .elementor-widget-toggle .elementor-toggle .elementor-tab-title .elementor-toggle-title,
        .elementor-widget-accordion .elementor-accordion .elementor-tab-title .elementor-accordion-icon i:before,
        .elementor-widget-toggle .elementor-toggle .elementor-tab-title .elementor-toggle-icon i:before,
        .filter-control-wrapper .filter-control-list .dots .dot,
        .error-404-title,        
        .single-product.woocommerce div.product .product_meta .product_meta_item a,
        .elementor-widget-image-box .elementor-image-box-wrapper .elementor-image-box-content .elementor-image-box-title,
        .elementor-widget-industrium_vertical_text .vertical-text,
        .industrium-image-slider-widget .slider-item-title,
        .elementor-widget-progress .elementor-widget-container .elementor-title,
        .elementor-widget-progress .elementor-progress-bar,
        .swiper-container .elementor-swiper-button i,
        .wp-block-search .wp-block-search__label,
        .wp-block-search.wp-block-search__button-inside .wp-block-search__inside-wrapper .wp-block-search__button.has-icon,
        .elementor-widget-industrium_custom_menu ul li a,
        .content-wrapper .wp-block-loginout,
        .content-wrapper .wp-block-loginout a,
        .block-editor-block-list__layout .wp-block-loginout,
        .block-editor-block-list__layout .wp-block-loginout a,
        .sidebar .shop-hidden-sidebar-close,
        .content-wrapper .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-color) .wp-block-social-link svg,
        .block-editor-block-list__layout .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-color) .wp-block-social-link svg,
        .single-post .post-meta-footer .post-meta-item.post-meta-item-tags a,        
        .single-post .post-meta-footer .post-meta-item-author,
        .single-post .post-meta-footer .post-meta-item-author a,
        .post-categories a.post-category-item:hover,
        .post-meta-header .post-meta-item .post-meta-item-day,
        .post-quote .post-quote-author,
        .team-item .team-item-socials .socials-trigger,
        .team-item .team-item-socials .team-socials.wrapper-socials a,        
        .industrium-price-item-widget .price-item.price-item-type-standard .price-item-title,
        .service-listing-wrapper .service-item .service-item-link,
        .elementor-widget-industrium_icon_box .icon-box-item-link,
        .elementor-widget-industrium_services_listing.view_type-1 .service-item .service-slider-item-link,
        .content-wrapper .mc4wp-form .mc4wp-form-fields input[type="submit"]:hover, 
        .content-wrapper .mc4wp-form .mc4wp-form-fields button:hover,
        .block-editor-block-list__layout .mc4wp-form .mc4wp-form-fields input[type="submit"]:hover, 
        .block-editor-block-list__layout .mc4wp-form .mc4wp-form-fields button:hover,
        .portfolio-slider-listing .portfolio-item-wrapper .post-title,
        .portfolio-slider-wrapper .archive-listing .slider-next-button-wrapper .slider-next-button,            
        .select2-container--default .select2-results__option[aria-selected=true], 
        .select2-container--default .select2-results__option[data-selected=true],
        .content-wrapper .select2-container--default .select2-results__option[aria-selected=true], 
        .content-wrapper .select2-container--default .select2-results__option[data-selected=true],
        .content-wrapper input[type="checkbox"]:checked:before,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"]:checked:before,
        .block-editor-block-list__layout  .select2-container--default .select2-results__option[aria-selected=true], 
        .block-editor-block-list__layout  .select2-container--default .select2-results__option[data-selected=true],
        .block-editor-block-list__layout  input[type="checkbox"]:checked:before,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"]:checked:before,
        .woocommerce form .form-row input[type="checkbox"].input-checkbox:checked:before,
        .industrium-content-slider-widget .bottom-area .content-slider-video .elementor-custom-embed-play .video-button-text,
        .industrium_tabs_widget .industrium_tabs_titles_container .industrium_tab_title_item a,
        .elementor-widget-industrium_button .industrium-button.button-type-2 {
            color: ' . esc_attr($standard_dark_text_color) . ';
        }
        .content-wrapper input[type="radio"]:checked:before,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="radio"]:checked:before,
        .block-editor-block-list__layout input[type="radio"]:checked:before,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="radio"]:checked:before {
            background-color: ' . esc_attr($standard_dark_text_color) . ';
        }
        .swiper-container .swiper-pagination-bullets .swiper-pagination-bullet.swiper-pagination-bullet-active,
        .swiper-container .swiper-pagination-bullets .swiper-pagination-bullet:after,
        .swiper-container-horizontal > .swiper-pagination-bullets .swiper-pagination-bullet.swiper-pagination-bullet-active, 
        .swiper-container-horizontal > .swiper-pagination-bullets .swiper-pagination-bullet:after,
        .industrium-price-item-widget .price-item.price-item-type-standard .price-item-custom-fields,
        .owl-dots .owl-dot.active span:before,
        .industrium-icon-box-widget > .icon-box-item.icon-box-header,
        .service-listing-wrapper .service-item .service-item-link {
            border-color: ' . esc_attr($standard_dark_text_color) . ';
        }
        .industrium-icon-box-widget .icon-box-item-link svg {
            fill: ' . esc_attr($standard_dark_text_color) . ';
        }
        .industrium_video_button_widget .eicon-play svg {
            stroke: ' . esc_attr($standard_dark_text_color) . ';
        }
    ';
}

$standard_light_text_color = industrium_get_prefered_option('standard_light_text_color');
if ( !empty($standard_light_text_color) ) {
    $industrium_custom_css .= '
        .post-meta-header .post-meta-item,
        .post-meta-header .post-meta-item a,
        .post-meta-item-tags,
        .content-wrapper .post-meta-item-tags a,
        .block-editor-block-list__layout .post-meta-item-tags a,
        .post-comment-date,
        div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider .wpforms-field-number-slider-hint,
        .widget_industrium_featured_posts_widget .featured-posts-item-date,
        .content-wrapper .wp-block-latest-posts li .wp-block-latest-posts__post-date,
        .widget_recent_entries ul li .post-date,
        .widget_recent_comments ul .recentcomments,
        .content-wrapper .wp-block-latest-comments li .wp-block-latest-comments__comment-meta,
        .content-wrapper .wp-block-latest-comments li .wp-block-latest-comments__comment-author,
        .block-editor-block-list__layout .wp-block-latest-posts li .wp-block-latest-posts__post-date,
        .block-editor-block-list__layout .wp-block-latest-comments li .wp-block-latest-comments__comment-meta,
        .block-editor-block-list__layout .wp-block-latest-comments li .wp-block-latest-comments__comment-author,
        .widget_recent_comments ul .recentcomments .comment-author-link > a,
        .widget_rss .rss-date,
        .wp-block-rss .wp-block-rss__item-publish-date,
        body .content-wrapper .gallery .gallery-item .gallery-caption,
        .block-editor-block-list__layout .gallery .gallery-item .gallery-caption,
        .post-navigation .post-navigation-categories,
        .post-navigation .post-navigation-categories a,
        .team-experience-item-period,
        .industrium-price-item-widget .price-item .price-item-custom-field,
        .widget_industrium_contacts_widget .field-label,
        .site-search .floating-placeholder,
        .form-fields .form-field.form-cookies,
        .single-service .help-item .help-item-title:after {
            color: ' . esc_attr($standard_light_text_color) . ';
        }
        .owl-dots .owl-dot span {
            background-color: ' . esc_attr($standard_light_text_color) . ';
        }
        .elementor-widget-industrium_special_text .special-text.special-text-effect-stroke {
            -webkit-text-stroke: 1px ' . esc_attr($standard_light_text_color) . ';
        }
        .industrium-icon-box-widget .icon-box-item-link .icon-box-header:before,        
        .industrium-icon-box-widget .icon-box-item-link:hover .icon-box-header:before,
        .service-listing-wrapper .service-item .service-post-title:before,
        .elementor-widget-image-box .elementor-image-box-content .elementor-image-box-title a:before,
        .elementor-widget-icon-box .elementor-icon-box-content .elementor-icon-box-title a:before {
            color: rgba(' . esc_attr(industrium_hex2rgb($standard_light_text_color)) . ', 0.6);
        }        
        .content-wrapper .input-floating-wrap .floating-placeholder,
        .content-wrapper input[type="text"]::-webkit-input-placeholder,
        .content-wrapper input[type="email"]::-webkit-input-placeholder,
        .content-wrapper input[type="url"]::-webkit-input-placeholder,
        .content-wrapper input[type="password"]::-webkit-input-placeholder,
        .content-wrapper input[type="search"]::-webkit-input-placeholder,
        .content-wrapper input[type="tel"]::-webkit-input-placeholder,
        .content-wrapper input[type="number"]::-webkit-input-placeholder, 
        .content-wrapper input[type="date"]::-webkit-input-placeholder, 
        .content-wrapper input[type="month"]::-webkit-input-placeholder, 
        .content-wrapper input[type="week"]::-webkit-input-placeholder, 
        .content-wrapper input[type="time"]::-webkit-input-placeholder, 
        .content-wrapper input[type="datetime"]::-webkit-input-placeholder, 
        .content-wrapper input[type="datetime-local"]::-webkit-input-placeholder, 
        .content-wrapper textarea::-webkit-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]::-webkit-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]::-webkit-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]::-webkit-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea::-webkit-input-placeholder,

        .block-editor-block-list__layout .input-floating-wrap .floating-placeholder,
        .block-editor-block-list__layout input[type="text"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="email"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="url"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="password"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="search"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="tel"]::-webkit-input-placeholder,
        .block-editor-block-list__layout input[type="number"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="date"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="month"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="week"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="time"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="datetime"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout input[type="datetime-local"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout textarea::-webkit-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]::-webkit-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]::-webkit-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]::-webkit-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea::-webkit-input-placeholder,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"]::-webkit-input-placeholder {
             color: ' . esc_attr($standard_light_text_color) . ';
        }
        
        .content-wrapper input[type="text"]:-moz-placeholder,
        .content-wrapper input[type="url"]:-moz-placeholder,
        .content-wrapper input[type="email"]:-moz-placeholder,
        .content-wrapper input[type="password"]:-moz-placeholder,
        .content-wrapper input[type="search"]:-moz-placeholder,
        .content-wrapper input[type="tel"]:-moz-placeholder,
        .content-wrapper input[type="number"]:-moz-placeholder, 
        .content-wrapper input[type="date"]:-moz-placeholder, 
        .content-wrapper input[type="month"]:-moz-placeholder, 
        .content-wrapper input[type="week"]:-moz-placeholder, 
        .content-wrapper input[type="time"]:-moz-placeholder, 
        .content-wrapper input[type="datetime"]:-moz-placeholder, 
        .content-wrapper input[type="datetime-local"]:-moz-placeholder, 
        .content-wrapper textarea:-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea:-moz-placeholder,

        .block-editor-block-list__layout input[type="text"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="url"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="email"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="password"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="search"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="tel"]:-moz-placeholder,
        .block-editor-block-list__layout input[type="number"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="date"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="month"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="week"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="time"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="datetime"]:-moz-placeholder, 
        .block-editor-block-list__layout input[type="datetime-local"]:-moz-placeholder, 
        .block-editor-block-list__layout textarea:-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea:-moz-placeholder,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"]:-moz-placeholder {
             color: ' . esc_attr($standard_light_text_color) . ';
        }
        
        .content-wrapper input[type="text"]::-moz-placeholder,
        .content-wrapper input[type="url"]::-moz-placeholder,
        .content-wrapper input[type="email"]::-moz-placeholder,
        .content-wrapper input[type="password"]::-moz-placeholder,
        .content-wrapper input[type="search"]::-moz-placeholder,
        .content-wrapper input[type="tel"]::-moz-placeholder,
        .content-wrapper input[type="number"]::-moz-placeholder, 
        .content-wrapper input[type="date"]::-moz-placeholder, 
        .content-wrapper input[type="month"]::-moz-placeholder, 
        .content-wrapper input[type="week"]::-moz-placeholder, 
        .content-wrapper input[type="time"]::-moz-placeholder, 
        .content-wrapper input[type="datetime"]::-moz-placeholder, 
        .content-wrapper input[type="datetime-local"]::-moz-placeholder, 
        .content-wrapper textarea::-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]::-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]::-moz-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]::-moz-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea::-moz-placeholder,

        .block-editor-block-list__layout input[type="text"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="url"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="email"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="password"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="search"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="tel"]::-moz-placeholder,
        .block-editor-block-list__layout input[type="number"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="date"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="month"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="week"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="time"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="datetime"]::-moz-placeholder, 
        .block-editor-block-list__layout input[type="datetime-local"]::-moz-placeholder, 
        .block-editor-block-list__layout textarea::-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]::-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]::-moz-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]::-moz-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea::-moz-placeholder,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"]::-moz-placeholder {
             color: ' . esc_attr($standard_light_text_color) . ';
        }
        
        .content-wrapper input[type="text"]:-ms-input-placeholder,
        .content-wrapper input[type="email"]:-ms-input-placeholder,
        .content-wrapper input[type="url"]:-ms-input-placeholder,
        .content-wrapper input[type="password"]:-ms-input-placeholder,
        .content-wrapper input[type="search"]:-ms-input-placeholder,
        .content-wrapper input[type="tel"]:-ms-input-placeholder,
        .content-wrapper input[type="number"]:-ms-input-placeholder, 
        .content-wrapper input[type="date"]:-ms-input-placeholder, 
        .content-wrapper input[type="month"]:-ms-input-placeholder, 
        .content-wrapper input[type="week"]:-ms-input-placeholder, 
        .content-wrapper input[type="time"]:-ms-input-placeholder, 
        .content-wrapper input[type="datetime"]:-ms-input-placeholder, 
        .content-wrapper input[type="datetime-local"]:-ms-input-placeholder, 
        .content-wrapper textarea:-ms-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:-ms-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:-ms-input-placeholder,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:-ms-input-placeholder, 
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea:-ms-input-placeholder,

        .block-editor-block-list__layout input[type="text"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="email"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="url"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="password"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="search"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="tel"]:-ms-input-placeholder,
        .block-editor-block-list__layout input[type="number"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="date"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="month"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="week"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="time"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="datetime"]:-ms-input-placeholder, 
        .block-editor-block-list__layout input[type="datetime-local"]:-ms-input-placeholder, 
        .block-editor-block-list__layout textarea:-ms-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:-ms-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:-ms-input-placeholder,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:-ms-input-placeholder, 
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea:-ms-input-placeholder,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"]:-ms-input-placeholder {
            color: ' . esc_attr($standard_light_text_color) . ';
        }
    ';
}

$standard_accent_text_color = industrium_get_prefered_option('standard_accent_text_color');
if ( !empty($standard_accent_text_color) ) {
    $industrium_custom_css .= '
        .content-wrapper a,  
        .block-editor-block-list__layout a,     
        ul > li:before,
        body .content-wrapper blockquote:before, 
        .block-editor-block-list__layout:before, 
        body .industrium_comments__item-text blockquote:before,
        .post-meta-header .post-meta-item a:hover,
        .content-wrapper .post-title a:hover,
        .content-wrapper .post-meta-item-tags a:hover,
        .block-editor-block-list__layout .post-title a:hover,
        .block-editor-block-list__layout .post-meta-item-tags a:hover,
        .single-post .post-meta-footer .post-meta-item-author a:hover,
        .widget_search .search-form .search-form-icon:hover,
        .widget_categories ul li:hover:before, 
        .widget_categories ul li:hover > a, 
        body .content-wrapper ul.wp-block-categories li:hover:before,
        body .content-wrapper ul.wp-block-categories li:hover > a,
        .block-editor-block-list__layout ul.wp-block-categories li:hover:before,
        .block-editor-block-list__layout ul.wp-block-categories li:hover > a,
        .widget_industrium_featured_posts_widget .featured-posts-item-link:hover,
        .widget_archive ul li:hover > a,
        .widget_archive ul > li:hover,
        .wp-block-archives li:hover > a,
        .wp-block-archives > li:hover,
        body .content-wrapper .wp-block-archives li:hover > a,
        body .content-wrapper .wp-block-archives > li:hover,
        .block-editor-block-list__layout .wp-block-archives li:hover > a,
        .block-editor-block-list__layout .wp-block-archives > li:hover,
        .widget_recent_entries ul li a:hover,
        .content-wrapper .wp-block-latest-posts li a:hover,
        .widget_recent_comments ul .recentcomments:before,
        .content-wrapper .wp-block-latest-comments li:before,
        .widget_recent_comments ul .recentcomments a:hover,
        .content-wrapper .wp-block-latest-comments li a:hover,
        body .content-wrapper .widget_calendar .wp-calendar-nav a:hover,
        body .content-wrapper .wp-block-calendar .wp-calendar-nav a:hover,
        .block-editor-block-list__layout .wp-block-latest-posts li a:hover,
        .block-editor-block-list__layout .wp-block-latest-comments li:before,
        .block-editor-block-list__layout .wp-block-latest-comments li a:hover,
        .block-editor-block-list__layout .widget_calendar .wp-calendar-nav a:hover,
        .block-editor-block-list__layout .wp-block-calendar .wp-calendar-nav a:hover,
        .widget_pages .widget-wrapper > ul li:hover > a,
        .widget_pages .widget-wrapper ul > li:hover:before,
        .widget_meta ul li:hover > a,
        .widget_meta ul li:hover:before,        
        .widget_tag_cloud .tagcloud .tag-cloud-link:hover,
        .wp-block-tag-cloud .tag-cloud-link:hover,
        .sidebar .widget .widget-title a:hover,
        .widget_rss ul a.rsswidget:hover,
        .wp-block-rss .wp-block-rss__item-title a:hover,
        .widget_industrium_contacts_widget .industrium-contacts-widget-field:before,
        .post-navigation .post-navigation-title a:hover,
        .post-navigation .post-navigation-categories a:hover,
        .post-navigation .archive-icon-link .archive-icon:hover,
        .team-short-info-position,
        .team-item .team-item-position,
        .service-item .service-post-title a:hover,
        .industrium-price-item-widget .price-item .price-item-custom-field.active:before,
        .industrium-step-widget .step-item .step-number,
        .elementor-widget-industrium_step_carousel .step-item .step-number,
        .industrium-testimonial-carousel-widget .testimonial-carousel-wrapper .author-position,
        .filter-control-wrapper .filter-control-list .dots .dot.active,
        .filter-control-wrapper .filter-control-list .dots .dot:hover,
        .single-product.woocommerce div.product .product_meta .product_meta_item a:hover,
        .wp-block-search.wp-block-search__button-inside .wp-block-search__inside-wrapper .wp-block-search__button.has-icon:hover,
        .elementor-widget-industrium_custom_menu ul li a:hover,
        .elementor-widget-industrium_custom_menu ul li.active a,
        .content-wrapper .wp-block-loginout a:hover,
        .block-editor-block-list__layout .wp-block-loginout a:hover,
        .sidebar .widget .widget-title:before, 
        .sidebar .widget .wp-block-search .wp-block-search__label:before, 
        .sidebar .widget .wc-block-product-search .wc-block-product-search__label:before, 
        .sidebar .widget .wp-block-group__inner-container > h1:first-child:before, 
        .sidebar .widget .wp-block-group__inner-container > h2:first-child:before, 
        .sidebar .widget .wp-block-group__inner-container > h3:first-child:before, 
        .sidebar .widget .wp-block-group__inner-container > h4:first-child:before, 
        .sidebar .widget .wp-block-group__inner-container > h5:first-child:before, 
        .sidebar .widget .wp-block-group__inner-container > h6:first-child:before,
        .widget_industrium_contacts_widget .industrium-contacts-widget-link:before,  
        .sidebar .widget div.wpforms-container-full .wpforms-form .wpforms-title:before,
        .sidebar .widget .wc-block-price-filter__title:before,     
        .post-categories a.post-category-item,
        .post-comment-wrapper.bypostauthor > .post-comment-item .post-comment-author:after,
        .industrium-format-quote .post-quote:before,
        .special-title .special-title-backward,
        .vacancy-post-meta .vacancy-post-meta-item,
        .vacancy-info .vacancy-salary .vacancy-salary-label, 
        .vacancy-item .vacancy-salary .vacancy-salary-label,
        .industrium-heading .industrium-subheading,
        .industrium-price-item-widget .price-item .price-item-container,
        .service-listing-wrapper .service-item .service-item-link:hover,
        .service-listing-wrapper .service-item .service-item-link:hover .service-post-title:before,
        .elementor-widget-industrium_icon_box .icon-box-item-link:hover,
        .content-wrapper.mc4wp-form .mc4wp-form-fields input[type="submit"], 
        .content-wrapper .mc4wp-form .mc4wp-form-fields button,
        .block-editor-block-list__layout.mc4wp-form .mc4wp-form-fields input[type="submit"], 
        .block-editor-block-list__layout .mc4wp-form .mc4wp-form-fields button,
        .elementor-widget-image-box .elementor-image-box-content .elementor-image-box-title a:hover:before,
        .elementor-widget-icon-box .elementor-icon-box-content .elementor-icon-box-title a:hover:before,
        .industrium-icon-box-widget .icon-box-item-link .icon-box-item.icon-box-header:after,
        .elementor-widget-industrium_image_carousel .slider-item .slider-item-arrow,
        .industrium_tabs_widget .industrium_tabs_titles_container .industrium_tab_title_item.active a {
            color: ' . esc_attr($standard_accent_text_color) . ';
        }      
        .widget_nav_menu ul li a:before, 
        .widget_industrium_nav_menu_widget ul li a:before,
        .elementor-widget-industrium_special_text .special-text.special-text-effect-fill,
        .elementor-widget-progress .elementor-progress-wrapper .elementor-progress-bar,
        .filter-control-wrapper .filter-control-list .dots .dot:after,
        .content-wrapper .wp-block-gallery .wp-block-image a:before,
        .block-editor-block-list__layout .wp-block-gallery .wp-block-image a:before,
        .post-meta-header .post-meta-item .post-meta-item-day,
        .vacancy-post-meta .vacancy-post-meta-item.vacancy-occupation,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"],
        .content-wrapper input[type="range"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"],
        .block-editor-block-list__layout input[type="range"],
        .industrium-content-slider-widget .bottom-area .slider-decoration:after,
        .industrium-content-slider-widget .industrium-heading .industrium-heading-content span[style*="text-decoration: underline"]:before, 
        .industrium-content-slider-widget .industrium-heading .industrium-heading-content u:before,
        .portfolio-slider-wrapper .archive-listing .slider-next-button-wrapper .slider-next-button,
        .elementor-widget-industrium_history_carousel .history-item-inner:after,
        .elementor-widget-industrium_services_listing.view_type-4 .service-item .service-slider-item-link:after {
            background-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .service-listing-wrapper .service-item .service-item-link:hover {
            border-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .team-experience-list .team-experience-item:before {
            color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-webkit-slider-thumb,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-webkit-slider-thumb {
            background-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-moz-range-thumb,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-moz-range-thumb {
             background-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-ms-thumb,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]::-ms-thumb {
             background-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]:focus::-ms-thumb,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .wpforms-field-number-slider input[type="range"]:focus::-ms-thumb {
             background-color: ' . esc_attr($standard_accent_text_color) . ';
        }
        .team-experience-list .team-experience-item-period,
        .industrium-step-widget .step-item .step-bg-number,
        .elementor-widget-industrium_step_carousel .step-item .step-bg-number,
        .history-item .history-year {
            -webkit-text-stroke: 1px ' . esc_attr($standard_accent_text_color) . ';
        }
        .elementor-widget-industrium_step_carousel.view_style-2 .step-item:hover .step-bg-number,
        .elementor-widget-industrium_step_carousel.view_style-3 .step-item:hover .step-bg-number {
            -webkit-text-fill-color:' . esc_attr($standard_accent_text_color) . ';
        }
        .industrium-price-item-widget .price-item .price-wrapper {
            text-shadow: 1px 1px 0 ' . esc_attr($standard_accent_text_color) . ', -1px -1px 0 ' . esc_attr($standard_accent_text_color) . ', 1px -1px 0 ' . esc_attr($standard_accent_text_color) . ', -1px 1px 0 ' . esc_attr($standard_accent_text_color) . ', 1px 1px 0 ' . esc_attr($standard_accent_text_color) . ';
        }
        .industrium-icon-box-widget .icon-box-item-link:hover svg {
            fill: ' . esc_attr($standard_accent_text_color) . ';
        }
        .industrium_video_button_widget .eicon-play:hover svg {
            stroke: ' . esc_attr($standard_accent_text_color) . ';
        }
    ';
}

$standard_border_color = industrium_get_prefered_option('standard_border_color');
if ( !empty($standard_border_color) ) {
    $industrium_custom_css .= '
        .simple-sidebar-trigger,
        .header-extra-socials.wrapper-socials a,
        .wp-block-search.wp-block-search__button-inside .wp-block-search__inside-wrapper,
        body .content-wrapper table tr td, 
        body .content-wrapper table tr th, 
        .block-editor-block-list__layout table tr td, 
        .block-editor-block-list__layout table tr th, 
        body .industrium_comments__item-text table tr td, 
        body .industrium_comments__item-text table tr th,
        .project-post-meta .project-post-meta-item,
        .vacancy-item,
        .single-service .benefits-wrapper .benefit-item,
        .service-listing-wrapper .service-item,

        .content-wrapper input[type="text"],
        .content-wrapper input[type="email"],
        .content-wrapper input[type="url"],
        .content-wrapper input[type="password"],
        .content-wrapper input[type="search"],
        .content-wrapper input[type="number"],
        .content-wrapper input[type="tel"],
        .content-wrapper input[type="range"],
        .content-wrapper input[type="date"],
        .content-wrapper input[type="month"],
        .content-wrapper input[type="week"],
        .content-wrapper input[type="time"],
        .content-wrapper input[type="datetime"],
        .content-wrapper input[type="datetime-local"],
        .content-wrapper input[type="color"],
        .content-wrapper .select-wrap,
        .content-wrapper textarea,

        .block-editor-block-list__layout input[type="text"],
        .block-editor-block-list__layout input[type="email"],
        .block-editor-block-list__layout input[type="url"],
        .block-editor-block-list__layout input[type="password"],
        .block-editor-block-list__layout input[type="search"],
        .block-editor-block-list__layout input[type="number"],
        .block-editor-block-list__layout input[type="tel"],
        .block-editor-block-list__layout input[type="range"],
        .block-editor-block-list__layout input[type="date"],
        .block-editor-block-list__layout input[type="month"],
        .block-editor-block-list__layout input[type="week"],
        .block-editor-block-list__layout input[type="time"],
        .block-editor-block-list__layout input[type="datetime"],
        .block-editor-block-list__layout input[type="datetime-local"],
        .block-editor-block-list__layout input[type="color"],
        .block-editor-block-list__layout .select-wrap,
        .block-editor-block-list__layout textarea,
        .select2-dropdown,
        body .select2-dropdown,
        .select2-container--default .select2-search--dropdown .select2-search__field,
        body .select2-container--default .select2-search--dropdown .select2-search__field,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form select,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .select-wrap,

        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form select,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .select-wrap,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"],
        .wp-block-search.wp-block-search__button-inside .wp-block-search__inside-wrapper,
        .project-listing-wrapper.project-slider-listing .slider-item,
        .project-listing-wrapper.project-slider-listing.view-type-2 .owl-item.active + .active .slider-item .project-item-content,
        .project-listing-wrapper.project-slider-listing.view-type-2 .owl-item.active + .active .slider-item .button-container {
            border-color: ' . esc_attr($standard_border_color) . ';
        }
        .content-wrapper div.wpforms-container-full .wpforms-form ul.wpforms-image-choices-classic label:not(.wpforms-error),
        .block-editor-block-list__layout div.wpforms-container-full .wpforms-form ul.wpforms-image-choices-classic label:not(.wpforms-error) {
            border-color: ' . esc_attr($standard_border_color) . ' !important;
        }
        select option:checked,
        div.wpforms-container-full .wpforms-form select option:checked,
        .select2-dropdown,
        body .select2-dropdown,
        .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected], 
        .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected], 
        .content-wrapper .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[aria-selected], 
        .block-editor-block-list__layout .select2-container--default .select2-results__option.select2-results__option--highlighted[data-selected],
        .project-listing-wrapper.project-slider-listing .slider-item:before {
            background-color: ' . esc_attr($standard_border_color) . ';
        }
    ';
}

$standard_border_hover_color = industrium_get_prefered_option('standard_border_hover_color');
if ( !empty($standard_border_hover_color) ) {
    $industrium_custom_css .= '
        .single-project .project-post-content .project-post-meta-wrapper,
        .content-wrapper input[type="text"]:focus,
        .content-wrapper input[type="email"]:focus,
        .content-wrapper input[type="url"]:focus,
        .content-wrapper input[type="password"]:focus,
        .content-wrapper input[type="search"]:focus,
        .content-wrapper input[type="number"]:focus,
        .content-wrapper input[type="tel"]:focus,
        .content-wrapper input[type="range"]:focus,
        .content-wrapper input[type="date"]:focus,
        .content-wrapper input[type="month"]:focus,
        .content-wrapper input[type="week"]:focus,
        .content-wrapper input[type="time"]:focus,
        .content-wrapper input[type="datetime"]:focus,
        .content-wrapper input[type="datetime-local"]:focus,
        .content-wrapper input[type="color"]:focus,
        .content-wrapper textarea:focus,
        .content-wrapper .select-wrap:focus-within,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form .select-wrap:focus-within,
        .block-editor-block-list__layout input[type="text"]:focus,
        .block-editor-block-list__layout input[type="email"]:focus,
        .block-editor-block-list__layout input[type="url"]:focus,
        .block-editor-block-list__layout input[type="password"]:focus,
        .block-editor-block-list__layout input[type="search"]:focus,
        .block-editor-block-list__layout input[type="number"]:focus,
        .block-editor-block-list__layout input[type="tel"]:focus,
        .block-editor-block-list__layout input[type="range"]:focus,
        .block-editor-block-list__layout input[type="date"]:focus,
        .block-editor-block-list__layout input[type="month"]:focus,
        .block-editor-block-list__layout input[type="week"]:focus,
        .block-editor-block-list__layout input[type="time"]:focus,
        .block-editor-block-list__layout input[type="datetime"]:focus,
        .block-editor-block-list__layout input[type="datetime-local"]:focus,
        .block-editor-block-list__layout input[type="color"]:focus,
        .block-editor-block-list__layout textarea:focus,
        .block-editor-block-list__layout .select-wrap:focus-within,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form .select-wrap:focus-within,
        .wp-block-search.wp-block-search__button-inside .wp-block-search__inside-wrapper:focus-within,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"]:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form select:focus,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"]:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form select:focus,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea:focus,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"]:focus,
        .content-wrapper .select2-container .select2-selection--single, 
        .block-editor-block-list__layout .select2-container .select2-selection--single, 
        .select2-container .select2-selection--single {
            border-color: ' . esc_attr($standard_border_hover_color) . ';
        }
    ';
}

$standard_background_color = industrium_get_prefered_option('standard_background_color');
if ( !empty($standard_background_color) ) {
    $industrium_custom_css .= '
        body,
        .simple-sidebar-trigger,
        .blog-item,
        .content-pagination .page-numbers, 
        .content-pagination .post-page-numbers,
        .content-wrapper input[type="text"],
        .content-wrapper input[type="email"],
        .content-wrapper input[type="url"],
        .content-wrapper input[type="password"],
        .content-wrapper input[type="search"],
        .content-wrapper input[type="number"],
        .content-wrapper input[type="tel"],
        .content-wrapper input[type="date"],
        .content-wrapper input[type="month"],
        .content-wrapper input[type="week"],
        .content-wrapper input[type="time"],
        .content-wrapper input[type="datetime"],
        .content-wrapper input[type="datetime-local"],
        .content-wrapper input[type="color"],
        .content-wrapper textarea,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form select,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form textarea,

        .block-editor-block-list__layout input[type="text"],
        .block-editor-block-list__layout input[type="email"],
        .block-editor-block-list__layout input[type="url"],
        .block-editor-block-list__layout input[type="password"],
        .block-editor-block-list__layout input[type="search"],
        .block-editor-block-list__layout input[type="number"],
        .block-editor-block-list__layout input[type="tel"],
        .block-editor-block-list__layout input[type="date"],
        .block-editor-block-list__layout input[type="month"],
        .block-editor-block-list__layout input[type="week"],
        .block-editor-block-list__layout input[type="time"],
        .block-editor-block-list__layout input[type="datetime"],
        .block-editor-block-list__layout input[type="datetime-local"],
        .block-editor-block-list__layout input[type="color"],
        .block-editor-block-list__layout textarea,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="text"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="email"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="url"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="password"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="search"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="number"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="tel"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="date"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="month"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="week"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="time"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="datetime-local"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="color"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form select,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form textarea,
        .select2-container--default .select2-results > .select2-results__options,
        .select2-container--default.select2-container--open .select2-selection,
        .select2-container--default.select2-container--open .select2-dropdown,
        .select2-container--default .select2-search--dropdown .select2-search__field,
        .content-wrapper .select2-container--default .select2-results > .select2-results__options,
        .content-wrapper .select2-container--default.select2-container--open .select2-selection,
        .block-editor-block-list__layout .select2-container--default .select2-results > .select2-results__options,
        .block-editor-block-list__layout .select2-container--default.select2-container--open .select2-selection,
        body .select2-container--default.select2-container--open .select2-dropdown,
        body .select2-container--default .select2-search--dropdown .select2-search__field,
        #form-preview .mc4wp-form .mc4wp-form-fields input[type="email"],
        .vacancy-item,
        .single-service .benefits-wrapper .benefit-item,
        .service-listing-wrapper .service-item,
        .industrium-price-item-widget .price-item.price-item-type-standard,
        .owl-theme .owl-nav [class*="owl-"],
        .industrium-content-slider-widget .owl-theme .owl-nav [class*="owl-"],
        .post-gallery-carousel.owl-carousel.owl-theme:hover .owl-nav  [class*="owl-"],
        .industrium-content-slider-widget .bottom-area .content-slider-video .elementor-custom-embed-play .eicon-play,
        .swiper-container .elementor-swiper-button i,
        .wp-video .mejs-overlay-play .mejs-overlay-button,
        .industrium-content-slider-widget .aside-area,
        .industrium-content-slider-widget .bottom-area .slider-decoration:before,
        .portfolio-slider-listing .portfolio-item-wrapper .portfolio-item-content .portfolio-item-content-inner,
        .portfolio-slider-listing .portfolio-item-wrapper .portfolio-item-link:hover .portfolio-item-content-inner,
        .industrium_video_button_widget .eicon-play,
        .single-post.industrium_case .post-meta-header .post-meta-item .post-meta-item-day,
        .results-boxes .result-boxes-decoration,
        .case-study-item-wrapper .post-meta-header .post-meta-item .post-meta-item-day,
        .decoration-widget .decoration-container .industrium-decoration > div,        
        .industrium-content-slider-widget .bottom-area .content-slider-video .elementor-custom-embed-play .video-button-text,
        .elementor-widget-industrium_services_listing.view_type-4 .service-item .service-slider-item-link:before {
            background-color: ' . esc_attr($standard_background_color) . ';
        }
        .industrium-price-item-widget .price-item .price-wrapper {
            color: ' . esc_attr($standard_background_color) . ';
        }
        .industrium-content-slider-widget .owl-theme .owl-nav [class*="owl-"],
        .swiper-container .elementor-swiper-button i {
            border-color: ' . esc_attr($standard_background_color) . ';
        }
    ';
}

$standard_background_alter_color = industrium_get_prefered_option('standard_background_alter_color');
if ( !empty($standard_background_alter_color) ) {
    $industrium_custom_css .= '
        .content-wrapper input[type="checkbox"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"],
        .block-editor-block-list__layout input[type="checkbox"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"],
        .woocommerce form .form-row input[type="checkbox"].input-checkbox,        
        .content-wrapper input[type="radio"],
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="radio"],
        .block-editor-block-list__layout input[type="radio"],
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="radio"],
        .industrium-format-quote .post-quote,

        .widget_industrium_banner_widget .banner-widget-wrapper.banner-default-colors,
        .section-accent-bg,
        .elementor-widget-progress .elementor-progress-wrapper,
        .wc-block-components-price-slider__range-input-progress {
            background-color: ' . esc_attr($standard_background_alter_color) . ';
        }
    ';
}

$standard_button_text_color = industrium_get_prefered_option('standard_button_text_color');
if ( !empty($standard_button_text_color) ) {
    $industrium_custom_css .= '
        body {
            --wpforms-button-text-color: ' . esc_attr($standard_button_text_color) . '
        }
        #form-preview button,        
        .industrium-button,
        .content-wrapper .industrium-button,
        .content-wrapper button:not(.customize-partial-edit-shortcut-button),
        .content-wrapper input[type="submit"],
        .content-wrapper input[type="button"],
        .content-wrapper input[type="reset"],
        .content-wrapper div.wpforms-container-full .wpforms-form input[type=submit], 
        .content-wrapper div.wpforms-container-full .wpforms-form button[type=submit], 
        .content-wrapper div.wpforms-container-full .wpforms-form .wpforms-page-button,
        .block-editor-block-list__layout .industrium-button,
        .widget_media_gallery .gallery .gallery-icon a:after,
        .widget_industrium_banner_widget .banner-widget-wrapper.banner-contrast-colors .industrium-button:hover,
        .widget_industrium_banner_widget .banner-widget-wrapper.banner-default-colors .industrium-button,
        .project-post-button .industrium-button:hover,
        .vacancy-post-button .industrium-button:hover,
        .vacancy-item-button .industrium-button:hover,
        #sb_instagram .sbi_item .sbi_photo:after,
        .swiper-container .elementor-swiper-button:hover i,
        .wp-block-gallery .blocks-gallery-grid .blocks-gallery-item a:after, 
        .media_gallery .blocks-gallery-grid .blocks-gallery-item a:after,
        body .content-wrapper .gallery .gallery-item .gallery-icon a:after,
        .block-editor-block-list__layout .gallery .gallery-item .gallery-icon a:after,
        .sidebar .wp-block-button:not(.is-style-fill) .wp-block-button__link:not(.has-text-color) {
            color: ' . esc_attr($standard_button_text_color) . ';
        }
    ';
}

$standard_button_border_color = industrium_get_prefered_option('standard_button_border_color');
if ( !empty($standard_button_border_color) ) {
    $industrium_custom_css .= '        
        .content-wrapper .wrapper-socials li,        
        .content-wrapper input[type="checkbox"]:checked,
        .content-wrapper div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"]:checked,
        .block-editor-block-list__layout .wrapper-socials li,        
        .block-editor-block-list__layout input[type="checkbox"]:checked,
        .block-editor-block-list__layout div.wpforms-container.wpforms-container-full .wpforms-form input[type="checkbox"]:checked,
        .woocommerce form .form-row input[type="checkbox"].input-checkbox:checked,
        .industrium-content-slider-widget .owl-theme .owl-nav [class*="owl-"]:not(.disabled):hover,
        .swiper-container .elementor-swiper-button:hover i,
        .content-wrapper .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-background-color) .wp-block-social-link,   
        .block-editor-block-list__layout .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-background-color) .wp-block-social-link,        
        .content-pagination .page-numbers, 
        .content-pagination .post-page-numbers,
        .elementor-widget-industrium_button .industrium-button.button-type-2 {
            border-color: ' . esc_attr($standard_button_border_color) . ';
        }
        .team-short-contact-button .industrium-button,
        .project-post-button .industrium-button,
        .vacancy-post-button .industrium-button,
        .vacancy-item-button .industrium-button,
        .content-wrapper input[type="submit"], 
        .content-wrapper input[type="button"], 
        .content-wrapper input[type="reset"],
        .content-wrapper button:not(.customize-partial-edit-shortcut-button),
        .content-wrapper div.wpforms-container-full .wpforms-form input[type=submit], 
        .content-wrapper div.wpforms-container-full .wpforms-form button[type=submit], 
        .content-wrapper div.wpforms-container-full .wpforms-form .wpforms-page-button,
        #form-preview button,
        .industrium-button,
        .content-wrapper .industrium-button,
        .block-editor-block-list__layout .industrium-button,
        .sidebar .wp-block-button:not(.is-style-fill) .wp-block-button__link:not(.has-background),
        .post-navigation .post-navigation-link a {
        	background-image: linear-gradient(0deg, ' . esc_attr($standard_button_border_color) . ' 0%, ' . esc_attr($standard_button_border_color) . ' 100%);
        }        
        .content-wrapper button:not(.customize-partial-edit-shortcut-button) svg,
        #form-preview button svg,
        .industrium-button svg,
        .content-wrapper .industrium-button svg,
        .block-editor-block-list__layout .industrium-button svg,
        .sidebar .wp-block-button:not(.is-style-fill) .wp-block-button__link:not(.has-background) svg {
        	stroke: ' . esc_attr($standard_button_border_color) . ';
        }
        .content-pagination .page-numbers:after,
        .content-pagination .post-page-numbers:after,
        .content-wrapper .wrapper-socials a:after,
        .content-wrapper .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-background-color) .wp-block-social-link:after,
        .block-editor-block-list__layout .wrapper-socials a:after,
        .block-editor-block-list__layout .wp-block-social-links:not(.is-style-logos-only):not(.is-style-pill-shape):not(.has-icon-background-color) .wp-block-social-link:after,
        .widget_media_gallery .gallery .gallery-icon a:before,
        #sb_instagram .sbi_item .sbi_photo:before,
        .owl-theme .owl-nav [class*="owl-"]:not(.disabled):hover,
        .industrium-content-slider-widget .owl-theme .owl-nav [class*="owl-"]:not(.disabled):hover,
        .post-gallery-carousel.owl-carousel.owl-theme .owl-nav [class*="owl-"]:not(.disabled):hover,
        .swiper-container .elementor-swiper-button:hover i,

        .select2-container--default .select2-results__option[aria-selected=true], 
        .select2-container--default .select2-results__option[data-selected=true],
        .content-wrapper .select2-container--default .select2-results__option[aria-selected=true], 
        .content-wrapper .select2-container--default .select2-results__option[data-selected=true],
        .block-editor-block-list__layout .select2-container--default .select2-results__option[aria-selected=true], 
        .block-editor-block-list__layout .select2-container--default .select2-results__option[data-selected=true],
        .elementor-widget-industrium_button .industrium-button.button-type-2:before,
        .elementor-widget-industrium_button .industrium-button.button-type-2 .industrium-button-text:before {
            background-color: ' . esc_attr($standard_button_border_color) . ';
        }
        .content-wrapper div.wpforms-container-full .wpforms-form ul.wpforms-image-choices-classic .wpforms-selected label,
        .block-editor-block-list__layout div.wpforms-container-full .wpforms-form ul.wpforms-image-choices-classic .wpforms-selected label {
            border-color: ' . esc_attr($standard_button_border_color) . ' !important;
        }
        .elementor-counter .elementor-counter-number-wrapper {
            -webkit-text-stroke: 1px ' . esc_attr($standard_button_border_color) . ';
        }
        .industrium-content-slider-widget .owl-carousel.owl-theme .slider-item:before,
        .wp-block-gallery .blocks-gallery-grid .blocks-gallery-item a:before, 
        .media_gallery .blocks-gallery-grid .blocks-gallery-item a:before,
        body .content-wrapper .gallery .gallery-item .gallery-icon a:before,
        .block-editor-block-list__layout .gallery .gallery-item .gallery-icon a:before {
             background-color: rgba(' . esc_attr(industrium_hex2rgb($standard_button_border_color)) . ', 0.5);
        }
        #form-preview button:after, 
        .industrium-button:after, 
        .content-wrapper button:not(.customize-partial-edit-shortcut-button):after, 
        .content-wrapper input[type="submit"]:after, 
        .content-wrapper input[type="button"]:after, 
        .content-wrapper input[type="reset"]:after,
        .block-editor-block-list__layout button:not(.customize-partial-edit-shortcut-button):after, 
        .block-editor-block-list__layout input[type="submit"]:after, 
        .block-editor-block-list__layout input[type="button"]:after, 
        .block-editor-block-list__layout input[type="reset"]:after,
        .industrium-content-slider-widget .bottom-area .content-slider-video .elementor-custom-embed-play .eicon-play:before,
        .sidebar .wp-block-button:not(.is-style-fill) .wp-block-button__link:not(.has-background):after {
            color: ' . esc_attr($standard_button_border_color) . ';
        }
    ';
}

$standard_button_background_color = industrium_get_prefered_option('standard_button_background_color');
if ( !empty($standard_button_background_color) ) {
    $industrium_custom_css .= '
        body {
            --wpforms-button-background-color: ' . esc_attr($standard_button_background_color) . '
        }
    ';
}

$standard_button_text_hover = industrium_get_prefered_option('standard_button_text_hover');
if ( !empty($standard_button_text_hover) ) {
    $industrium_custom_css .= '
        .sticky .post-labels:before, 
        .status-sticky .post-labels:before,
        .single-post .post-meta-footer .post-meta-item.post-meta-item-tags a:hover,
        .industrium-button:hover,
        .content-wrapper .industrium-button:hover,
        .content-wrapper button:not(.customize-partial-edit-shortcut-button):hover,
        .content-wrapper input[type="submit"]:hover,
        .content-wrapper input[type="button"]:hover,
        .content-wrapper input[type="reset"]:hover,
        .content-wrapper div.wpforms-container-full .wpforms-form input[type=submit]:hover, 
        .content-wrapper div.wpforms-container-full .wpforms-form button[type=submit]:hover, 
        .content-wrapper div.wpforms-container-full .wpforms-form .wpforms-page-button:hover,
        .block-editor-block-list__layout .industrium-button:hover,
        .widget_industrium_banner_widget .banner-widget-wrapper.banner-contrast-colors .industrium-button,
        .widget_industrium_banner_widget .banner-widget-wrapper.banner-default-colors .industrium-button:hover,
        .project-post-button .industrium-button,
        .vacancy-post-button .industrium-button,
        .vacancy-item-button .industrium-button,
        .single-service .help-item.active .help-item-title:after,
        .industrium-step-widget .step-item .step-bg-number,
        .elementor-widget-industrium_step_carousel .step-item .step-bg-number,
        .elementor-widget-accordion .elementor-accordion .elementor-tab-title.elementor-active .elementor-accordion-title,
        .elementor-widget-toggle .elementor-toggle .elementor-tab-title.elementor-active .elementor-toggle-title,
        .elementor-widget-accordion .elementor-accordion .elementor-tab-title.elementor-active .elementor-accordion-icon i:before,
        .elementor-widget-toggle .elementor-toggle .elementor-tab-title.elementor-active .elementor-toggle-icon i:before,
        .sidebar .wp-block-button:not(.is-style-fill) .wp-block-button__link:not(.has-text-color):hover {
            color: ' . esc_attr($standard_button_text_hover) . ';
        }
    ';
}

$standard_button_border_hover = industrium_get_prefered_option('standard_button_border_hover');
if ( !empty($standard_button_border_hover) ) {
    $industrium_custom_css .= '
        
    ';
}

$standard_button_background_hover = industrium_get_prefered_option('standard_button_background_hover');
if ( !empty($standard_button_background_hover) ) {
    $industrium_custom_css .= '       
        
    ';
}